version: "3.9"

services:

  db:
    image: mysql:latest
    container_name: simple-theme-mysql
    command: --sort_buffer_size=512K --wait_timeout=800 --max_allowed_packet=512M --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/dump:/docker-entrypoint-initdb.d
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - app-network
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: simple-theme-phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.backend=phpmyadmin"
      - "traefik.frontend.rule=Host:(`${PHPMYADMIN_URL}`)"
    ports:
      - ${PHPMYADMIN_PORT}:80
    networks:
      - app-network
    restart: unless-stopped

  wordpress:
    image: wordpress:latest
    container_name: simple-theme-wordpress
    build:
      context: ./php
      args:
        PROJECT_FILES: ${PROJECT_FILES}
        PHP_VERSION: ${PHP_VERSION}
        WORDPRESS_VERSION: ${WORDPRESS_VERSION}
        USER_ID: ${USER_ID}
    volumes:
      - ${WP_PATH}:${PROJECT_FILES}
      - ./php/conf.ini:/usr/local/etc/php/conf.d/conf.ini
    environment:
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG}
      WORDPRESS_URL: ${WORDPRESS_URL}
      WORDPRESS_PORT: ${MYSQL_PORT}
      WORDPRESS_CONFIG_EXTRA: |
        define( 'FS_METHOD', 'direct' );
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    image: nginx:1.23.0-alpine
    container_name: simple-theme-nginx
    depends_on:
      - wordpress
    volumes:
      - ${WP_PATH}:${PROJECT_FILES}
      - ./nginx/templates:/etc/nginx/templates
    environment:
      NGINX_ROOT: ${PROJECT_FILES}
      NGINX_PORT: 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`${BASE_URL}`)"
      - "traefik.http.routers.nginx.entrypoints=web"
    networks:
      - app-network
    restart: unless-stopped

  traefik:
    image: traefik:latest
    container_name: simple-theme-traefik
    depends_on:
      - nginx
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - ${TRAEFIK_PORT}:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge